site_name: Stream2Prompt

nav:
  - Home: index.md
  - Model Lab:
    - Environment Setup: Model-Lab/Environment-Setup.md
    - Usage: Model-Lab/Usage.md
  - Model-API:
    - Environment Setup: Model-API/Environment-Setup.md
    - Usage: Model-API/Usage.md
