import torch

print("CUDA available:", torch.cuda.is_available())
print("CUDA device count:", torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    print(f"Device {i}: {torch.cuda.get_device_name(i)}")
print("Current CUDA device:", torch.cuda.current_device())
x = torch.rand(5, 3).cuda()
print("Tensor on CUDA:", x)
print("Tensor device:", x.device)
y = torch.rand(5, 3).cpu()
print("Tensor on CPU:", y)
print("Tensor device:", y.device)
z = x + y.cuda()
print("Result of addition:", z)
print("Result device:", z.device)
print("CUDA test completed successfully.")
print("PyTorch version:", torch.__version__)
print("Torchvision version:", torch.__version__)
print("Torchaudio version:", torch.__version__)
print("Torch CUDA version:", torch.version.cuda)
print("Torch CUDNN version:", torch.backends.cudnn.version())
